### ISSUE TITLE
Add CONFIG option to ign_find_package

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-cmake#114]
The [ign_find_package](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/cmake/IgnUtils.cmake#L3-L15) macro supports several options that are passed through to `find_package` ([like `QUIET` and `EXACT`](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/cmake/IgnUtils.cmake#L156-L162)). Until recently (https://github.com/ignitionrobotics/ign-physics/pull/119), ignition-physics has been passing `CONFIG` to `ign_find_package(DART)`, intending it as a pass-through option but is now passing it using the `EXTRA_ARGS` parameter. I think it would be useful to support `CONFIG` is as a pass-through parameter similar to `QUIET` and `EXACT`.

**Comment by harshmahesheka** [comment]
I have created a pr https://github.com/ignitionrobotics/ign-cmake/pull/211 for this issue here.

**Comment by adlarkin** [comment]
Closing this since #211 has been merged.
