### ISSUE TITLE
codecheck target uses python instead of python3

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-cmake#116]
It looks like [IgnCodeCheck](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/cmake/IgnCodeCheck.cmake#L5) is using `python` instead of `python3`, which may be a problem on Ubuntu 20.04. We should probably switch this to `python3`.

**Comment by adlarkin** [comment]
Would fixing this be as simple as changing [line 5 of `IgnCodeCheck.cmake`](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/cmake/IgnCodeCheck.cmake#L5) to `find_program(PYTHON_PATH python3)`?

**Comment by scpeters** [comment]
> @mjcarroll @scpeters Would fixing this be as simple as changing [line 5 of `IgnCodeCheck.cmake`](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/cmake/IgnCodeCheck.cmake#L5) to `find_program(PYTHON_PATH python3)`?

you would also need to change line 50 and confirm that [our fork of cpplint.py](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/codecheck/cpplint.py) supports python3
