### ISSUE TITLE
Deprecate utilities in favor of ign-utils

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-cmake#171]
The [ign-utils](https://github.com/ignitionrobotics/ign-utils/) package has been created to hold general purpose utilities that have minimal dependencies and are useful for multiple libraries. We've already moved the [SuppressWarning](https://github.com/ignitionrobotics/ign-utils/blob/ign-utils1/include/ignition/utils/SuppressWarning.hh) functionality there.

I think we should also move the `ExtraTestMacros` and to `ign-utils` and deprecate the `utilities` component of this package. I can see an argument for keeping that here close to other test configurations though. My main concern is that this repository is not well suited to hold C++ code. We have created a new namespace, `utilities`, which doesn't match the rest of this library. We aren't generating test coverage for it, etc. I think it's a cleaner separation of concerns if we leave C++ code out of `ign-cmake`.

## Desired behavior

On `ign-cmake3`, using `ignition::utilities` generates deprecation warnings. On `ign-cmake4`, the component is removed.

I suggest this with the full understanding that `ign-cmake4` may only be released in 2078 :upside_down_face: 

My short-term suggestion is to migrate these utilities to `ign-utils` and stop using the ones from `ign-cmake`, even though they're not officially deprecated on `ign-cmake2`.

## Alternatives considered

We could just keep `ExtraTestMacros` here... That would certainly involve less effort. My main concern is that we forget the separation of concerns and start adding more header-only functionality here, when it should go to `ign-utils`.

## Implementation suggestion

1. Add `ExtraTestMacros` to `ign-utils`
2. Migrate all uses of `utilities` to use `ign-utils`
3. Remove all dependencies on the `utilities` component from Fortress
4. Initiate the tick-tock of utilities suggested above.

## Additional context

See #18 for why the utilities were added in the first place.

**Comment by mjcarroll** [comment]
This copies `ExtraTestMacros` into ign-utils: https://github.com/ignitionrobotics/ign-utils/pull/37

**Comment by chapulina** [comment]
Fully deprecated as of #233
