### ISSUE TITLE
Proposal: Adding C++ utilities to ign-cmake

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-cmake#18]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/18)) by Michael Grey (Bitbucket: [mxgrey](https://bitbucket.org/%7Bc1cdfe52-2887-474c-ae99-72fdc53a59c9%7D/), GitHub: [mxgrey](https://github.com/mxgrey)).**

----------------------------------------
Apologies in advance for the wall-of-text.

The original motivation for creating `ign-cmake` was to systematically ensure consistent build behavior across all the ignition projects, in a way that is maintainable and scalable.

Even though the `ign-cmake` package is still in development, it's had some very tangible benefits: we now have four projects (`ign-math`, `ign-common`, `ign-msgs`, and `ign-transport`) with robust build systems across all of our supported platforms and consistent package behavior across all of the projects. If we ever decide to change our packaging behavior or if we ever need to fix a build system bug, we can take care of it in `ign-cmake`, and all the ignition projects will benefit the next time they configure. Future and upcoming projects will experience these benefits as well.

However, we want to have consistency across all the ignition projects in more ways than just their build system and packaging. The most obvious example is the PIMPL pattern, which is a design pattern that we aim to use across all the ignition projects to achieve maximum flexibility in our development cycles without needing to be concerned about breaking ABI.

The forcing function that prompted me to make this proposal was in a recent `ign-transport` pull request, we found ourselves repeatedly writing boilerplate move and copy constructors, plus move and copy assignment operators for just about every darn interface class (here's a sampling from that one pull request: [1](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/Batch.hhT44) [2](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/Descriptor.hhT109) [3](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/Log.hhT48) [4](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/MsgIter.hhT45) [5](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/MsgIter.hhT49) [6](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/MsgIter.hhT57) [7](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT85) [8](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT89) [9](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT152) [10](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT156) [11](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT198) [12](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT202) [13](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT242) [14](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/QueryOptions.hhT246) [15](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/Recorder.hhT57) [16](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/SqlStatement.hhT52) [17](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/SqlStatement.hhT56) [18](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/SqlStatement.hhT61) [19](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-requests/252/wip-ignition-tools-record-playback/diff#Llog/include/ignition/transport/log/SqlStatement.hhT66)).

The worst part is, even with all that effort in manually creating all those constructors and assignment operators, some of the classes in that pull request *still* don't have proper copy and move semantics, simply because we have not yet noticed that their copy/move constructors/operators are missing.

That's when I remembered some [design utilities](http://oliora.github.io/2015/12/29/pimpl-and-rule-of-zero.html) promoted by Scott Meyers which makes the PIMPL pattern so very much more bearable. Here's a tl;dr of that article:

Instead of using a plain `std::unique_ptr<Implementation>` to contain the implementation object, you can have a `impl_ptr<Implementation>` which takes care of creating the copy and move constructors for your interface class. To make that more concrete, your class definition would look like this:

```
class MyClass
{
  public: /* Interface functions go here */

  private: class Implementation;
  private: ImplPtr<Implementation> dataPtr;
};
```

Then in the source file, your constructor would look like this:

```
MyClass::MyClass( /* constructor args */ )
  : dataPtr(MakeImpl<Implementation>(/* constructor args */))
{
  // Do nothing
}
```

This will allow `MyClass` to automatically create a copy constructor, move constructor, copy operator, and move operator, and all you have to do is replace `std::unique_ptr` with `ImplPtr` and `new Implementation` with `MakeImpl<Implementation>`. Note that we can also have a `UniqueImplPtr` which will allow moving but not copying, for classes that are not copyable. The catch, of course, is you need to have access to the header that defines `ImplPtr` and `MakeImpl`.

Since it's a single header file, the brute force approach would be to write the header and then drop it into each project. That's a viable solution if we're confident that we'll never ever have to make any changes to the implementation, but that's a very risky assumption to make.

Ideally, we would want the `ImplPtr` to be available in every project from a single source. We already have a project which is a required dependency of every ignition project: `ign-cmake`. If we were to consider the goal of `ign-cmake` to be achieving consistent, maintainable, scalable development (not just build+packaging behavior) across all the ignition projects, then it would make sense to have it provide a small set of C++ utilities that could be used across all projects to keep behavior and development consistent between them.

I can think of three utilities which would make sense to share across all projects right away: (1) the pimpl class mentioned here, (2) the warning suppression system which is currently in `ign-common`, and (3) the Console utility currently in `ign-common`. These are things that all project would benefit from:

1. Anything that can make PIMPL easier to stomach is a good thing.

2. We're repeatedly dealing with the same compiler warnings across every project. This would give us a clean way to handle those consistently everywhere.

3. Having the `Console` class and its error/warning macros as base utilities would allow us to have consistent status, warning, and error messaging behavior across all the libraries, instead of having some print proper messages while others print plain, unformatted messages.

We could also consider the `Filesystem` from `ign-common`, but I don't think that's as basic of a utility (and it will probably be replaced by the C++17 filesystem soon anyway).

### Why not just use ign-common?

Right now, `ign-common` would be more aptly named `ign-miscellaneous`. Most of its content is not common to all projects, and it would be unreasonable to have all projects depend on it, even after it's been split into components.

`ign-cmake` is already a required dependency. Putting these utilities into `ign-cmake` will make them accessible to all projects right away, without introducing any new dependencies.

### Then could we really call this project ign-cmake anymore?

Maybe not.

I would propose that we add these utilities to `ign-cmake` as a library called `ignition-utilities` (or maybe `ignition-utils`, or some variation on that). When each project calls `find_package(ignition-cmake1)` it will import a target for the `ignition-utilities` library, and `ign-cmake` can automatically link each project library against the utilities target. Consumer projects wouldn't have to change *anything* in their build scripts.

Then, when we're approaching the hypothetical release of `ignition-cmake1`, we can decide whether we want to keep using the name `ignition-cmake`. Maybe by then, `ign-common` will be rid of its miscellaneous components, and we can have `ign-cmake` take over the name `ign-common`. Otherwise, we could consider renaming `ign-cmake` to something like `ign-utilities`, `ign-utils`, `ign-root`, `ign-base`, or any other suggestions that people have. Or we could just keep the name as `ign-cmake` and accept the slight misnomer of the project.

**Comment by chapulina** [comment]
A few months after this issue was ticketed, the [utilities](https://github.com/ignitionrobotics/ign-cmake/tree/ign-cmake2/include/ignition/utilities) component was added to `ign-cmake` with the suppression warnings.

3 years later, on Ignition Edifice, we added the [ign-utils](https://github.com/ignitionrobotics/ign-utils/) package to serve this purpose, so we don't stretch the responsibility of `ign-cmake` and it can remain focused on build utilities. The `ign-utils` package is already used by libraries that don't directly depend on `ign-cmake`, like `libSDFormat`.

The PIMPL pointer helper is already on `ign-utils`, as well as the suppression macros. See #171 about deprecating the utilities in this repository.

I'm closing this issue in favor of putting new C++ utilities into `ign-utils`.
