### ISSUE TITLE
FindIgnOGRE2: It finds Ogre 13.x.

### ISSUE THREAD

**Issue by mahiuchun** [ignitionrobotics/ign-cmake#205]
## Environment
* OS Version: Arch Linux with `ogre` 13.2.4-1 installed.

## Description
* Expected behavior: It fails to find Ogre2.
* Actual behavior: It incorrectly finds Ogre2.

## Steps to reproduce

1. Clone this repo.
2. `cd examples/find_ogre2/ogre-2.2`
3. `cmake -Bbuild`

**Comment by mjcarroll** [comment]
It looks like now that the ogre/ogre-next split is done, they are dropping the major and switching to semver.

We should account for this moving forward.

https://www.ogre3d.org/2021/08/14/ogre-13-released
