### ISSUE TITLE
IgnOGRE2 support for ogre-next in Ubuntu Jammy

### ISSUE THREAD

**Issue by j-rivero** [ignitionrobotics/ign-cmake#208]
Ubuntu jammy provides a [libogre-next package ](https://packages.ubuntu.com/uk/jammy/libogre-next-dev) that ships a custom CMake helper that can potentially work mostly on its own (see the [patch](https://github.com/ignition-release/ign-rendering6-release/pull/8/files#diff-93975c3b98779e4d395782d26e01fdfe517a184b37ed202723eb0c57ebcb6cfd) used for ign-rendering code).

## Desired behavior
IgnOGRE2 to support the Ubuntu Jammy ogre-next installation.

## Alternatives considered
Until now, the alternative is to patch code to avoid IgnOGRE2 and use CMake diretly.

## Implementation suggestion
Try to support the Ubuntu jammy versions transparently with the other installations existing out there.

## Additional context
The root of the problem is the design of OGRE-Next to be an embedded piece of software inside other projects. This is hard to workaround and the origin of the IgnOGRE2 module.

**Comment by scpeters** [comment]
something seems odd about the cmake version detection for `libogre-next-dev`. I just tried configuring cmake on a 22.04 container with a small patch to search for the `OGRE-Next` cmake package, and I see the following, noting the `version: unknown`:

~~~
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c0b903d0..a19804b0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -97,7 +97,7 @@ endif()
 
 #--------------------------------------
 # Find OGRE2
-ign_find_package(IgnOGRE2 VERSION 2.2.0
+ign_find_package(OGRE-Next VERSION 2.2.0
     COMPONENTS HlmsPbs HlmsUnlit Overlay
     REQUIRED_BY ogre2
     PRIVATE_FOR ogre2)
~~~

~~~
CMake Warning at /usr/share/cmake/ignition-cmake2/cmake2/IgnUtils.cmake:189 (find_package):
  Could not find a configuration file for package "OGRE-Next" that is
  compatible with requested version "2.2.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/OGRE-Next/OGRE-NextConfig.cmake, version: unknown
    /lib/x86_64-linux-gnu/cmake/OGRE-Next/OGRE-NextConfig.cmake, version: unknown
~~~
