### ISSUE TITLE
ign_find_package VERSION argument has no effect

### ISSUE THREAD

**Issue by mjcarroll** [ignitionrobotics/ign-cmake#214]
## Environment
* OS Version: Ubuntu 20.04
* Source and binary
    
## Details

Experimenting with using the `VERSION` argument in `ign_find_package` call to enforce minimum versions, and it doesn't seem to have any impact on versions that are found or the control flow in cmake.

For example:

```
#------------------------------------
# Find avutil
ign_find_package(AVUTIL 
  VERSION 55.78.100 
  REQUIRED_BY av 
  PRETTY libavutil)
```

Yields:
```
-- Checking for module 'libavutil'
--   Found libavutil, version 56.31.100
-- Found AVUTIL: TRUE (Required is at least version "55.78.100") 
-- Looking for libavutil - found
```

But also:
```
#------------------------------------
# Find avutil
ign_find_package(AVUTIL 
  VERSION 1000.1000.1000
  REQUIRED_BY av 
  PRETTY libavutil)
```

Yields:
```
-- Checking for module 'libavutil'
--   Found libavutil, version 56.31.100
-- Found AVUTIL: TRUE (Required is at least version "1000.1000.1000") 
-- Looking for libavutil - found
```

I would expect in the second case, `libavutil` should not be found because the requested version doesn't match exactly and also is substantially higher.

Is there something wrong with my usage here?

**Comment by mxgrey** [comment]
It seems [`FindAVUTIL.cmake`](https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/FindAVUTIL.cmake) is just implemented in way too simplistic of a way for the behavior that you want. The implementation appears to be intentionally version-agnostic.

We could pass the version information into [`ign_pkg_check_modules_quiet(...)`](https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/FindAVUTIL.cmake#L19), but if that search fails then I think it will fall back onto [this block](https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/FindAVUTIL.cmake#L21-L26) which will ignore the version number anyway.

So you're not doing anything wrong; the implementation of the find-module needs to be changed to get the behavior that you're expecting.

**Comment by scpeters** [comment]
here's an example that does do a version check:

* https://github.com/ignitionrobotics/ign-cmake/blob/c34873d6c6bb301d5a865497483f4399d84c28b8/cmake/FindSQLite3.cmake#L28-L32

**Comment by mjcarroll** [comment]
Thanks for the pointers, I will address this in a follow up PR and close this, as it is not a real issue anymore.
