### ISSUE TITLE
Exclude doc target from being executed automatically in all builds

### ISSUE THREAD

**Issue by j-rivero** [ignitionrobotics/ign-cmake#228]
Mostly enabling https://github.com/ignitionrobotics/ign-cmake/pull/144 ON by default to exclude the doc generation to be run in all the builds. Executing docs in all the builds done for all the use case scenarios seems too much overhead (specially in big software projects like ign-gazebo) to be added by default.

**Comment by azeey** [comment]
Fixed by #434.
