### ISSUE TITLE
MIGRATION.md and Migration.md cause problems on non-case-sensitive filesystems

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-cmake#241]
## Environment
* OS Version: macOS 10.15
* Source or binary build? source build of `main` branch as of bf61d3b44c2ef0b3179a5d1d569e0106e33b6f5e

## Description

* Expected behavior: `git clone` should show a clean repository
* Actual behavior: there is a modified file even after running `git reset --hard`

By default, macOS does not use a case-sensitive filesystem (same for Windows), so cloning `ign-cmake` only allows one of `Migration.md` or `MIGRATION.md` to exist. These files should be merged or one of them renamed.

## Steps to reproduce

1. `git clone https://github.com/ignitionrobotics/ign-cmake -b main`
2. `git status` should be clean but it's not
3.

**Comment by scpeters** [comment]
`Migration.md` was added in https://github.com/ignitionrobotics/ign-cmake/pull/233

**Comment by chapulina** [comment]
Ah yeah I figured this may become an issue. See

* https://github.com/ignitionrobotics/ign-cmake/pull/242

**Comment by scpeters** [comment]
fixed by https://github.com/ignitionrobotics/ign-cmake/pull/242
