### ISSUE TITLE
Compilation failing when performing codecheck

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-cmake#62]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/62)) by João André (Bitbucket: [joaocandre](https://bitbucket.org/%7Bdac47269-c26c-4a4f-8c51-673d2bb1f16e%7D/)).**

----------------------------------------
I’m trying to compile ‘ignition-cmake’ and compilation failing with

```
[ 15%] Performing codecheck step for 'core_no_deps_Debug'
Scanning dependencies of target codecheck
make[6]: *** [CMakeFiles/codecheck.dir/build.make:59: CMakeFiles/codecheck] Error 1
make[5]: *** [CMakeFiles/Makefile2:142: CMakeFiles/codecheck.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:149: CMakeFiles/codecheck.dir/rule] Error 2
make[3]: *** [Makefile:201: codecheck] Error 2
make[2]: *** [examples/CMakeFiles/core_no_deps_Debug.dir/build.make:124: examples/core_no_deps_Debug-prefix/src/core_no_deps_Debug-stamp/core_no_deps_Debug-codecheck] Error 2
make[1]: *** [CMakeFiles/Makefile2:1232: examples/CMakeFiles/core_no_deps_Debug.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

The output does not give me any information as to what exactly is failing? 

I’m building this on Archlinux though the AUR’s PKGBUILD file \([archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ignition-cmake](http://archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ignition-cmake)\).

**Comment by scpeters** [comment]
workaround with `-DBUILD_TESTING=OFF`
