### ISSUE TITLE
Support for work without pkg-config for FindUUID

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-cmake#64]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/64)) by Silvio Traversaro (Bitbucket: [traversaro](https://bitbucket.org/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D/)).**

----------------------------------------
# Summary

Add code to permit to FindUUID to work even without `pkg-config` installed in the system.

# Motivation

At the moment the FindUUID CMake scripts assume that `pkg-config` is installed in the system to work. This is a reasonable assumption, as FindUUID is supposed to work only on \*nix systems. However, unfortunately the vcpkg continuous integration on Linux does not have/require pkg-config installed, and so the stock FindUUID fails on that machine, see [https://github.com/microsoft/vcpkg/pull/8044#issuecomment-529515227](https://github.com/microsoft/vcpkg/pull/8044#issuecomment-529515227) . For this reason, it may be convient to support this case.

# Describe alternatives you've considered

Leave the patch just in the vcpkg port: as in almost all other cases `pkg-config` will be installed, it make sense that the burden of maintenance of this case remains on the vcpkg side.

# Additional context

The patch is already available in vcpkg at [https://github.com/microsoft/vcpkg/pull/8044/files#diff-d3ef7f499fd629bfd6d5029bf3847dea](https://github.com/microsoft/vcpkg/pull/8044/files#diff-d3ef7f499fd629bfd6d5029bf3847dea) , but I am not sure if it is of general interest, so I will open a PR only if there is interest.

**Comment by traversaro** [comment]
Clearly when packaging  ignition-cmake2 for vcpkg ( https://github.com/microsoft/vcpkg/pull/10014 ) I had completely forgot this patch, and now the dependent ports  are not finding uuid .

**Comment by traversaro** [comment]
This was fixed in https://github.com/ignitionrobotics/ign-cmake/pull/95, so we can close the issue.
